export type Service = {
  slug: string
  name: string
  tagline: string
  metaDescription: string
  intro: string
  bullets: string[]
  conditions?: string[]
  whyUs: string
  faqs: { q: string; a: string }[]
}

export const services: Service[] = [
  {
    slug: 'home-visit',
    name: 'Home Visit',
    tagline: 'Your vet comes to you — AED 400 + VAT.',
    metaDescription: "Vet home visit in Dubai — AED 400 + VAT. Mike's Vet sends an experienced vet to your home for consultations, vaccinations, health checks and more. Covering JVC, Al Barsha, The Springs, Jumeirah, DAMAC Hills, Mudon and surrounding areas.",
    intro: "Some pets do better at home than in a clinic. Cats that hide for days after a vet visit, dogs that go into overdrive in a waiting room, senior pets who find the car ride painful — for all of them, a home visit changes everything. One of our experienced vets comes to you, examines your pet in their own space, and provides the same quality of care you'd receive in our clinic on Hessa Street. AED 400 + VAT per visit.",
    bullets: [
      'Consultations and health assessments',
      'Vaccinations (core and non-core)',
      'Wellness and senior health checks',
      'Chronic condition monitoring and medication administration',
      'Post-operative check-ups and wound assessment',
      'Multi-pet households — see all your pets in one visit',
      'Covering JVC, Al Barsha, Barsha Heights, The Springs, Jumeirah, Motor City, Arabian Ranches, DAMAC Hills, Mudon, and surrounding areas',
    ],
    conditions: [
      'Cats and anxious dogs who stress badly at the clinic',
      'Senior or mobility-impaired pets',
      'Post-surgical recovery check-ups',
      'Chronic conditions requiring regular monitoring',
      'Multi-pet households',
      'Owners with limited mobility or no transport',
    ],
    whyUs: "Our home visit vets are the same experienced team who work in our clinic — not agency locums. You get a vet who understands your pet's history and can coordinate seamlessly with our in-house team if follow-up diagnostics or treatment is needed.",
    faqs: [
      { q: 'How much does a vet home visit cost in Dubai?', a: "Our home visit fee is AED 400 + VAT. This covers the visit itself. Consultations, vaccinations, or treatments are charged separately at our standard clinic rates — you'll always be told the cost before anything is done." },
      { q: 'Which areas of Dubai do you cover for home visits?', a: "We cover JVC, Al Barsha, Barsha Heights, The Springs, Jumeirah, Motor City, Arabian Ranches, DAMAC Hills, Mudon, and surrounding areas. If you're unsure whether we reach you, call or WhatsApp us on +971 4 283 7744." },
      { q: 'What can be done during a home visit?', a: "Consultations, vaccinations, health and wellness checks, senior pet assessments, post-operative check-ups, chronic condition monitoring, and medication administration. We come prepared for routine clinical work." },
      { q: 'What can\'t be done at home?', a: "Anything that requires our in-clinic equipment — surgery, dental procedures, blood tests, X-ray, ultrasound, or emergency treatment. If we identify something at home that needs further investigation, we'll book your pet into the clinic and our records follow them." },
      { q: 'Can you visit my home for a cat that hates the carrier?', a: "Absolutely — this is one of the most common reasons owners book a home visit. Cats examined in their own territory are typically calmer, which means a more thorough and accurate examination for the vet too." },
      { q: 'How do I book a vet home visit?', a: "Call or WhatsApp us on +971 4 283 7744, or book online at mikesvet.com. Let us know your location and what you'd like seen — we'll confirm availability and arrange a time that works for you." },
    ],
  },
  {
    slug: 'vaccinations',
    name: 'Vaccinations',
    tagline: 'Protection your pet can count on — tailored to life in Dubai.',
    metaDescription: "Cat and dog vaccinations in Dubai at Mike's Vet, Hessa Street. Core and non-core vaccines, puppy and kitten schedules, rabies, bordetella and more. Book online.",
    intro: "Dubai's climate and lifestyle expose pets to risks that differ from other countries. Our vets design vaccination schedules that reflect your pet's age, breed, indoor/outdoor exposure, and travel history — giving them the right protection at the right time.",
    bullets: [
      'Core vaccines: FVRCP (cats), DHPPiL (dogs)',
      'Rabies vaccination (required for UAE travel and boarding)',
      'Non-core vaccines: FeLV, Bordetella, Leptospirosis',
      'Puppy and kitten primary course',
      'Adult annual and triennial boosters',
      'Digital vaccination records and reminders',
    ],
    whyUs: "Our international team of vets stays current with UAE import and travel regulations, so your vaccination record is always export-ready if you plan to travel with your pet.",
    faqs: [
      { q: 'What vaccinations does my cat need in Dubai?', a: "Cats in Dubai should receive the FVRCP (feline viral rhinotracheitis, calicivirus, panleukopenia) core vaccine, a rabies vaccine, and — if they go outdoors or board — the FeLV (feline leukaemia) vaccine. Our vets will recommend the right schedule at your first visit." },
      { q: 'How often does my dog need vaccines in Dubai?', a: "Dogs need a primary course as puppies, then annual or triennial boosters depending on the vaccine. Rabies is required annually or every three years depending on the product used. We send reminders when your pet is due." },
      { q: 'Can I bring my pet to Dubai without vaccinations?', a: "No. UAE import regulations require a valid rabies vaccine (at least 21 days before travel) and a microchip. Additional vaccines may be required depending on your country of origin." },
      { q: 'Do you vaccinate rabbits and other small animals?', a: "We primarily vaccinate cats and dogs. For rabbits and exotic pets, please call us to discuss your specific needs." },
    ],
  },
  {
    slug: 'consultations',
    name: 'Consultations',
    tagline: 'Expert advice from vets who listen — not just vets who prescribe.',
    metaDescription: "Book a vet consultation in Dubai at Mike's Vet, Hessa Street. Experienced vets for cats and dogs, open 7 days 9am–9:30pm. Same-day appointments available.",
    intro: "A good consultation starts with listening. Our vets take time to understand your pet's full history, lifestyle, and your concerns before examining them. Whether it's a new symptom, a behaviour change, or a second opinion you're after, we give you clear answers — not jargon.",
    bullets: [
      'General health consultations for cats and dogs',
      'New pet health assessments',
      'Second opinion consultations',
      'Pre-travel and export health checks',
      'Senior pet health consultations',
      'Behavioural concerns and referrals',
    ],
    whyUs: "With vets from 6 countries on our team, we bring diverse training and perspectives to every case. Our consultations are unhurried — we don't rush you out the door.",
    faqs: [
      { q: 'How do I book a vet consultation at Mike\'s Vet?', a: "You can book online at mikesvet.com, WhatsApp us on +971 4 283 7744, or call us directly. We are open 7 days a week from 9am to 9:30pm." },
      { q: 'Do you offer same-day vet appointments in Dubai?', a: "Yes, we do our best to accommodate same-day appointments. Call or WhatsApp us in the morning and we will do everything we can to see your pet that day." },
      { q: 'What should I bring to my pet\'s first consultation?', a: "Bring any previous vaccination records, medical history, and a list of any medications your pet is currently taking. If possible, bring a fresh urine or stool sample if your pet has digestive or urinary symptoms." },
      { q: 'Can I get a second opinion at Mike\'s Vet?', a: "Absolutely. We welcome second opinion consultations. Bring any previous test results, X-rays, or medical records and our vets will give you an independent assessment." },
    ],
  },
  {
    slug: 'wellness-checks',
    name: 'Wellness Checks',
    tagline: 'Catch problems early. Keep your pet healthier, longer.',
    metaDescription: "Annual pet wellness checks in Dubai at Mike's Vet. Head-to-toe health assessments for cats and dogs — detect issues early. Open 7 days on Hessa Street.",
    intro: "Pets age faster than humans and can't tell you when something feels off. An annual wellness check gives our vets the chance to examine your pet head-to-toe, baseline their health, and catch anything brewing before it becomes a serious problem — saving you stress and cost down the line.",
    bullets: [
      'Full physical examination (eyes, ears, skin, coat, joints, abdomen)',
      'Weight and body condition scoring',
      'Dental health assessment',
      'Parasite screening and prevention advice',
      'Blood pressure check (especially for seniors)',
      'Age-specific health advice',
    ],
    conditions: ['Obesity and weight management', 'Early kidney or liver changes', 'Heart murmurs', 'Dental disease', 'Arthritis in senior pets', 'Thyroid conditions (cats)'],
    whyUs: "We keep a complete health record for your pet across every visit, so we can spot trends over time — not just one-off snapshots.",
    faqs: [
      { q: 'How often should I bring my cat or dog for a wellness check?', a: "We recommend annual wellness checks for adult pets and twice-yearly for seniors (7+ years for cats, 6+ years for large dogs). Puppies and kittens need more frequent visits during their first year." },
      { q: 'What is included in a pet wellness check?', a: "A full physical exam covering eyes, ears, mouth, skin, heart, lungs, abdomen, joints, and lymph nodes. We also assess weight and body condition, discuss parasite prevention, and flag any age-related concerns." },
      { q: 'Should I fast my pet before a wellness check?', a: "Not usually for a standard wellness exam. If we recommend blood work, we may ask you to withhold food for 4–6 hours beforehand. We'll let you know in advance." },
    ],
  },
  {
    slug: 'dental-care',
    name: 'Dental Care',
    tagline: "Bad breath is a symptom, not just a nuisance.",
    metaDescription: "Pet dental cleaning and oral care in Dubai at Mike's Vet. Professional teeth cleaning, dental X-rays, extractions, and gum disease treatment for cats and dogs.",
    intro: "Over 80% of dogs and 70% of cats over age three have some form of dental disease — and most owners don't know until it's advanced. Dental disease causes pain, affects eating, and can damage the kidneys, heart, and liver. Our dental care goes beyond a clean: we diagnose and treat the underlying condition.",
    bullets: [
      'Professional ultrasonic dental scaling and polishing',
      'Dental X-rays to assess root and bone health',
      'Tooth extractions (simple and surgical)',
      'Gum disease (periodontal) treatment',
      'Oral tumour and lesion assessment',
      'Home dental care advice and product recommendations',
    ],
    conditions: ['Periodontal disease', 'Tooth resorption (cats)', 'Fractured teeth', 'Oral masses', 'Gingivitis', 'Retained deciduous teeth (puppies/kittens)'],
    whyUs: "All dental procedures are performed under general anaesthesia with full monitoring — we don't do 'anaesthesia-free dentals' as they don't allow proper cleaning below the gumline where disease lives.",
    faqs: [
      { q: 'How do I know if my pet needs a dental clean?', a: "Signs include bad breath, yellow or brown tartar on the teeth, red or swollen gums, drooling, difficulty eating, or pawing at the mouth. Our vets assess dental health at every consultation and wellness check." },
      { q: 'Is pet dental cleaning safe under anaesthesia?', a: "Yes, when performed by experienced vets with full monitoring. We use modern anaesthetic protocols and monitor your pet's oxygen, blood pressure, heart rate, and temperature throughout." },
      { q: 'How often should my pet have a professional dental clean?', a: "It depends on the individual. Some pets need annual cleans, others every two to three years. Regular home brushing significantly extends the time between professional cleans." },
      { q: 'Can I brush my cat\'s teeth at home?', a: "Yes, and we recommend it. We'll show you how to introduce tooth brushing gradually and recommend pet-safe toothpaste. Even a few times a week makes a meaningful difference." },
    ],
  },
  {
    slug: 'spay-neuter',
    name: 'Spay & Neuter',
    tagline: 'A simple procedure with lifelong benefits.',
    metaDescription: "Cat and dog spay and neuter in Dubai at Mike's Vet. Safe sterilisation surgery, experienced vets, full anaesthetic monitoring. Book your pet's procedure online.",
    intro: "Spaying and neutering are among the most impactful things you can do for your pet's long-term health. Beyond preventing unwanted litters, these routine procedures significantly reduce the risk of certain cancers, eliminate life-threatening reproductive emergencies, and often lead to calmer, healthier pets.",
    bullets: [
      'Cat spay (ovariohysterectomy) and castration',
      'Dog spay (ovariohysterectomy) and castration',
      'Pre-surgical blood screen and health assessment',
      'Full anaesthetic monitoring throughout',
      'Pain management and post-op care plan',
      'Recovery check-up included',
    ],
    whyUs: "We use modern multimodal pain management — before, during, and after surgery — so your pet is comfortable throughout recovery, not just during the procedure.",
    faqs: [
      { q: 'What is the best age to spay or neuter my cat or dog?', a: "For cats, we generally recommend 5–6 months. For dogs, it varies by breed and size — smaller dogs earlier, larger breeds often benefit from waiting until skeletal maturity. Your vet will advise the right timing for your pet." },
      { q: 'How long is the recovery after spay or neuter surgery?', a: "Most cats and dogs are comfortable and moving around within 24–48 hours. Full recovery takes around 10–14 days, during which you'll need to restrict vigorous exercise and keep the incision site clean and dry." },
      { q: 'Is spay or neuter surgery risky?', a: "These are routine procedures with very low complication rates when performed by experienced vets with proper monitoring. We carry out a pre-surgical health check and blood screen to ensure your pet is fit for anaesthesia." },
      { q: 'Will my pet gain weight after being spayed or neutered?', a: "Sterilisation can slow metabolism slightly, but weight gain is not inevitable. With appropriate diet and exercise, your pet will maintain a healthy weight. We can advise on post-neuter nutrition." },
    ],
  },
  {
    slug: 'soft-tissue-surgery',
    name: 'Soft Tissue Surgery',
    tagline: 'Advanced surgical expertise — close to home.',
    metaDescription: "Complex soft tissue surgery for cats & dogs in Dubai at Mike's Vet. Tumour removal, GI surgery, bladder, caesarean, and emergency surgery — experienced veterinary surgeons on Hessa Street. No referral needed.",
    intro: "From a small skin lump to complex abdominal surgery, our team is equipped to handle a wide range of soft tissue procedures in-house. Having an experienced surgical team on Hessa Street means your pet gets faster care — without the stress and cost of specialist referrals for many conditions.",
    bullets: [
      'Mass and tumour removal',
      'Gastrointestinal surgery (intestinal obstruction, stomach, intestines)',
      'Bladder and urinary tract surgery',
      'Respiratory surgery',
      'Wound repair and reconstructive surgery',
      'Caesarean sections',
      'Perineal urethrostomy (cats)',
    ],
    conditions: ['Lipomas and skin tumours', 'Intestinal foreign bodies', 'Bladder stones', 'Hernias', 'Pyometra (emergency uterine infection)', 'Tracheal collapse'],
    whyUs: "Our surgical team trained in multiple countries and brings international-standard techniques to Dubai. We use up-to-date anaesthetic protocols and have a dedicated surgical suite with full monitoring equipment.",
    faqs: [
      { q: 'What soft tissue surgeries do you perform at Mike\'s Vet?', a: "We perform a wide range of soft tissue procedures including mass removals, gastrointestinal surgery, bladder surgery, wound repair, caesareans, and more. Contact us to discuss your pet's specific needs." },
      { q: 'Do I need a referral for surgery at Mike\'s Vet?', a: "No referral is needed. You can book a surgical consultation directly with us and our vets will assess your pet and recommend the appropriate procedure." },
      { q: 'How do I prepare my pet for surgery?', a: "We will give you specific pre-operative instructions at your consultation. Generally, you will need to withhold food from midnight the night before and water from the morning of surgery. Full written instructions will be provided." },
    ],
  },
  {
    slug: 'imaging-xray',
    name: 'Imaging & X-Ray',
    tagline: 'In-house imaging means answers today — not next week.',
    metaDescription: "Digital X-ray and ultrasound for pets in Dubai at Mike's Vet. Mindray Vetus9 ultrasound with cardiology suite, digital radiography, same-day results. Hessa Street, open 7 days.",
    intro: "When your pet is unwell, waiting days for imaging results is not an option. Our clinic runs a Mindray Vetus9 — one of the most advanced veterinary ultrasound platforms available — alongside digital radiography, giving our vets a detailed diagnostic picture within minutes, without sending you to an external imaging centre.",
    bullets: [
      'Mindray Vetus9 ultrasound — Zone Sonography Technology (ZST+) for exceptional image clarity',
      'Tissue Doppler, contrast imaging, and Natural Touch Elastography',
      'Full cardiology suite — echocardiography, Auto EF, TDI for heart assessment',
      'High-frequency linear probes for small-structure and superficial imaging',
      'Digital radiography (X-ray) — chest, abdomen, limbs, spine',
      'Pregnancy confirmation, guided fine needle aspirates',
      'Same-day results — no external referral required',
    ],
    conditions: ['Respiratory disease', 'Heart enlargement or fluid', 'Abdominal masses', 'Bladder stones', 'Fractures', 'Foreign body ingestion', 'Pregnancy', 'Cardiac disease'],
    whyUs: "The Mindray Vetus9 is the same platform used in leading referral hospitals. Having it in-house at Hessa Street means your vet reads the images themselves — no miscommunication, no waiting, no second visit.",
    faqs: [
      { q: 'What ultrasound machine does Mike\'s Vet use?', a: "We use the Mindray Vetus9 — a premium veterinary ultrasound platform with Zone Sonography Technology (ZST+), tissue Doppler, contrast imaging, elastography, and a full cardiology suite including echocardiography. It's the same level of technology found in specialist referral centres." },
      { q: 'Does my pet need sedation for an X-ray?', a: "Not always. Many cooperative pets can be X-rayed without sedation. For painful or anxious pets, or when precise positioning is needed, light sedation may be recommended for their comfort and image quality." },
      { q: 'How long does a pet ultrasound take?', a: "A standard abdominal ultrasound takes around 20–40 minutes depending on what we are looking at. Your pet may need to have their fur clipped in a small area for the probe to make contact with the skin." },
      { q: 'Can you do a heart ultrasound (echocardiogram) for my pet?', a: "Yes. Our Mindray Vetus9 has a dedicated cardiology suite with echocardiography capability, Tissue Doppler Imaging (TDI), and automated ejection fraction (Auto EF) measurement — allowing our vets to assess heart size, function, and blood flow in detail." },
    ],
  },
  {
    slug: 'orthopaedic-surgery',
    name: 'Orthopaedic Surgery',
    tagline: 'Getting your pet back on their feet.',
    metaDescription: "Orthopaedic surgery for dogs & cats in Dubai at Mike's Vet. TPLO (cruciate ligament), fracture repair, luxating patella & hip dysplasia by an experienced surgical team on Hessa Street. Open 7 days, no referral needed.",
    intro: "Bone and joint conditions cause significant pain and limit your pet's quality of life. Our orthopaedic surgical team handles a broad range of skeletal conditions, from fractures to cruciate ligament repairs, using modern surgical techniques that prioritise a full, comfortable recovery. No specialist referral needed: we perform complex orthopaedic surgery in-house on Hessa Street.",
    bullets: [
      'Fracture repair (external fixation, plates, pins)',
      'TPLO — cruciate ligament surgery (gold-standard CCL repair)',
      'Luxating patella correction',
      'Hip dysplasia management',
      'Arthroscopy',
      'Limb deformity correction',
      'Post-operative physiotherapy guidance',
    ],
    conditions: ['Cranial cruciate ligament (CCL) rupture', 'Luxating patella', 'Hip dysplasia', 'Long bone fractures', 'Joint infection', 'Bone tumours'],
    whyUs: "Our orthopaedic and surgical cases are led by 🇮🇪 Dr. Nick Stokes DVM GPCert SAS, 🇮🇹 Dr. Debora Ferraris DVM (Improve International Small Animal Surgery), and 🇩🇿 Dr. Feth Mazari DVM (GP Cert in Ultrasound). Between them they bring a wealth of international surgical experience to Hessa Street. You get skilled, confident surgical care without the cost or wait of a specialist referral centre.",
    faqs: [
      { q: 'Does Mike\'s Vet perform orthopaedic surgery for dogs in Dubai?', a: "Yes. Mike's Vet performs a full range of orthopaedic procedures for dogs and cats including TPLO (cruciate ligament repair), fracture fixation, luxating patella correction, and hip dysplasia management. Our surgical team includes Dr. Nick Stokes DVM GPCert SAS, Dr. Debora Ferraris DVM (Improve International Small Animal Surgery), and Dr. Feth Mazari DVM." },
      { q: 'My dog is limping — does it need orthopaedic surgery?', a: "Not necessarily. Limping can have many causes from soft tissue injuries to joint disease. We'll perform a thorough clinical examination and X-rays to determine the cause and recommend the most appropriate treatment — which may or may not be surgery." },
      { q: 'What is TPLO surgery and does Mike\'s Vet perform it?', a: "TPLO (Tibial Plateau Levelling Osteotomy) is the gold-standard surgical treatment for cranial cruciate ligament (CCL) rupture in dogs. It changes the biomechanics of the knee so the ruptured ligament is no longer needed for stability. Contact us to discuss whether your dog is a candidate." },
      { q: 'Where can I get TPLO surgery for my dog in Dubai?', a: "Mike's Vet on Hessa Street, Dubai performs TPLO surgery for dogs with cruciate ligament (CCL) rupture. Our surgical team includes Dr. Nick Stokes DVM GPCert SAS and Dr. Debora Ferraris DVM (Improve International Small Animal Surgery). Call or WhatsApp +971 4 283 7744 to arrange a consultation." },
      { q: 'How long is the recovery from orthopaedic surgery?', a: "Recovery varies significantly by procedure. Fracture repair may need 6–12 weeks of restricted exercise, while joint procedures like TPLO typically require 12–16 weeks of controlled rehabilitation. We provide a detailed written recovery plan with every surgical case." },
      { q: 'What are the signs my dog needs cruciate ligament surgery?', a: "Common signs of a ruptured cruciate (CCL) in dogs include: sudden hind leg lameness after exercise, a 'sit test' where the dog avoids bending the knee when sitting, muscle loss in the affected leg, and joint swelling. A vet examination and X-rays are needed to confirm the diagnosis." },
    ],
  },
  {
    slug: 'in-house-laboratory',
    name: 'In-House Laboratory',
    tagline: 'Hospital-grade diagnostics — results while you wait.',
    metaDescription: "In-house pet laboratory in Dubai at Mike's Vet. Full IDEXX suite (CBC, chemistry, SediVue, SNAP), Zoetis Vetscan Imagyst AI diagnostics, and PCR testing. Hessa Street, open 7 days.",
    intro: "Our diagnostic laboratory is equipped to reference-laboratory standard — in-house, on Hessa Street. We run the full IDEXX suite alongside the Zoetis Vetscan Imagyst AI platform and PCR testing, giving your vet comprehensive results within the same appointment. No waiting 24–48 hours for an external lab when your pet is sick.",
    bullets: [
      'IDEXX ProCyte — full CBC with HD laser cell-by-cell analysis',
      'IDEXX Catalyst One — comprehensive chemistry panel (25+ tests including organ function, electrolytes, T4) in 8 minutes',
      'IDEXX SediVue Dx — automated urine sediment analysis in 30 seconds, AI-powered with 70 high-res images per sample',
      'IDEXX SNAP rapid tests — heartworm, FIV/FeLV, parvovirus, Giardia, feline pancreatic lipase',
      'Zoetis Vetscan Imagyst — AI fecal parasite detection (eggs, cysts, oocysts) in 9 minutes; AI blood smear and digital cytology',
      'PCR testing for infectious disease (feline herpesvirus, calicivirus, Chlamydophila, canine respiratory panel, and more)',
      'Pre-anaesthetic blood screening',
    ],
    conditions: ['Kidney and liver disease', 'Diabetes', 'Anaemia', 'Infection and sepsis', 'Intestinal parasites', 'Thyroid disease (cats)', 'Urinary tract disease', 'Pre-surgical screening'],
    whyUs: "Most practices run one or two in-house analyzers. We run a full diagnostic suite — IDEXX CBC, chemistry, urine sediment, SNAP, Vetscan Imagyst AI, and PCR — so your vet rarely has to send anything out and wait.",
    faqs: [
      { q: 'What laboratory equipment does Mike\'s Vet have?', a: "We run the full IDEXX suite — ProCyte CBC analyzer, Catalyst One chemistry analyzer (25+ tests in 8 minutes), SediVue Dx automated urine sediment, and SNAP rapid tests. We also have the Zoetis Vetscan Imagyst AI platform for fecal parasite detection, blood smear analysis, and cytology, plus PCR testing for infectious disease." },
      { q: 'How quickly do blood test results come back?', a: "IDEXX Catalyst One chemistry results take around 8 minutes. CBC results from the ProCyte are similarly rapid. In most cases your vet can discuss results and begin treatment within the same appointment." },
      { q: 'Can you test for intestinal parasites in-house?', a: "Yes. The Zoetis Vetscan Imagyst uses AI image recognition to detect parasite eggs, cysts, and oocysts in fecal samples with results in 9 minutes — the same accuracy as a board-certified parasitologist." },
      { q: 'Does my pet need to fast before a blood test?', a: "For a biochemistry panel, we recommend withholding food for 4–6 hours. Water is fine. For an emergency or basic screen, we can run tests without fasting if needed." },
      { q: 'What does a pre-anaesthetic blood screen check for?', a: "It assesses kidney and liver function, red and white blood cell counts, and clotting indicators — to ensure your pet can safely metabolise the anaesthetic drugs before any procedure." },
    ],
  },
  {
    slug: 'ophthalmology',
    name: 'Ophthalmology',
    tagline: 'Specialist eye care for cats and dogs in Dubai.',
    metaDescription: "Veterinary ophthalmology in Dubai at Mike's Vet. Eye examinations, treatment for infections, ulcers, glaucoma, cataracts, and more for cats and dogs. Hessa Street.",
    intro: "Eye conditions in pets can escalate quickly — what looks like simple redness can be glaucoma causing irreversible damage within hours. Our vets are experienced in diagnosing and managing a full range of ocular conditions, with specialist equipment for thorough eye examinations.",
    bullets: [
      'Full ophthalmic examination (slit lamp, ophthalmoscopy)',
      'Intraocular pressure measurement (tonometry)',
      'Fluorescein staining for corneal ulcers',
      'Schirmer tear test for dry eye',
      'Entropion and ectropion surgical correction',
      'Eyelid mass removal',
      'Management of chronic eye conditions',
    ],
    conditions: ['Conjunctivitis', 'Corneal ulcers', 'Dry eye (KCS)', 'Glaucoma', 'Cataracts', 'Uveitis', 'Entropion (inturned eyelids)', 'Cherry eye'],
    whyUs: "Eye conditions require prompt, accurate diagnosis. Our vets have the equipment and experience to assess your pet's eyes properly — not just treat symptoms.",
    faqs: [
      { q: 'My cat has a weepy eye — should I be worried?', a: "Ocular discharge can range from mild conjunctivitis to more serious conditions like corneal ulcers or herpesvirus. It's always worth having it checked, as some conditions worsen rapidly without treatment." },
      { q: 'Can you treat glaucoma in dogs?', a: "Yes. Glaucoma treatment depends on the cause and severity. We can manage medical glaucoma with eye drops and monitor intraocular pressure, or refer for specialist surgery when required." },
      { q: 'My dog\'s eye looks cloudy — what does that mean?', a: "Cloudiness can indicate cataracts, corneal disease, or inflammation inside the eye. A tonometry test helps rule out glaucoma, which is a painful emergency. Book an appointment as soon as possible." },
    ],
  },
  {
    slug: 'nutrition-care',
    name: 'Nutrition Care',
    tagline: 'The right diet is the foundation of everything.',
    metaDescription: "Pet nutrition counselling in Dubai at Mike's Vet. Personalised dietary plans for cats and dogs — weight management, therapeutic diets, life stage nutrition. Hessa Street.",
    intro: "What your pet eats directly affects their weight, energy, coat, organ health, and longevity. Yet nutrition is one of the most confusing areas for pet owners, with conflicting advice online and in pet shops. Our vets take a clinical approach — tailoring diet recommendations to your pet's specific age, breed, condition, and health needs.",
    bullets: [
      'Body condition scoring and weight assessment',
      'Weight loss programmes for overweight pets',
      'Prescription and therapeutic diet planning',
      'Life stage nutrition (puppy, adult, senior)',
      'Food allergy and intolerance management',
      'Raw and home-cooked diet assessment',
      'Renal, cardiac, and hepatic diet management',
    ],
    whyUs: "We don't sell food — we give independent dietary advice based on your pet's clinical needs. No brand bias, no commission.",
    faqs: [
      { q: 'How do I know if my cat or dog is overweight?', a: "We use a body condition score (BCS) — a standardised scale from 1–9. A score of 5 is ideal. You can roughly assess at home: you should be able to feel your pet's ribs easily without pressing hard. Our vets assess this at every consultation." },
      { q: 'Is raw food good for cats and dogs?', a: "Raw diets can be nutritionally complete when properly formulated, but carry risks of bacterial contamination and nutritional imbalance if not done correctly. We can review your pet's current diet and advise on safety and suitability." },
      { q: 'My pet has been diagnosed with kidney disease — what should I feed them?', a: "Renal disease requires a carefully managed diet, typically low in phosphorus and controlled protein. We prescribe therapeutic renal diets and adjust recommendations based on your pet's bloodwork and disease stage." },
    ],
  },
  {
    slug: 'emergency-care',
    name: 'Emergency & Critical Care',
    tagline: 'When every minute counts — we\'re ready.',
    metaDescription: "Emergency and critical care vet in Dubai at Mike's Vet. Full ICU unit with oxygen therapy, IV support, emergency surgery, and in-house diagnostics. Open 7 days 9am–9:30pm on Hessa Street.",
    intro: "Pets don't schedule emergencies. When something goes wrong — a sudden collapse, difficulty breathing, suspected poisoning, or a serious injury — you need a vet equipped to act immediately. Our clinic on Hessa Street combines emergency stabilisation with full critical care capability: in-house diagnostics, emergency surgery, IV support, and a dedicated ICU unit for patients who need continued intensive monitoring.",
    bullets: [
      'Urgent triage and clinical stabilisation',
      'Oxygen therapy and IV fluid support',
      'Emergency surgery capability in-house',
      'In-house blood testing, X-ray, and ultrasound for rapid diagnosis',
      'Full ICU unit — controlled oxygen (21–65%), temperature, humidity, UV sterilisation, and nebulisation therapy',
      'Toxin and poisoning management',
      'Trauma assessment and wound care',
      'Continuous critical monitoring throughout',
    ],
    conditions: ['Urinary blockage (cats)', 'Gastric dilatation-volvulus (bloat) in dogs', 'Respiratory distress', 'Suspected poisoning', 'Road traffic accidents', 'Severe vomiting or diarrhoea', 'Collapse or seizures', 'Pyometra', 'Post-surgical critical recovery', 'Parvovirus'],
    whyUs: "We have everything under one roof — lab, X-ray, ultrasound, surgical suite, and a dedicated ICU unit — so your pet gets assessed, treated, and monitored in one place during a crisis. No transfers, no gaps in care.",
    faqs: [
      { q: 'What should I do if my pet has an emergency?', a: "Call us immediately on +971 4 283 7744 or WhatsApp us. Let us know you're coming and the nature of the emergency so we can prepare. Keep your pet as calm and still as possible during transport." },
      { q: 'Does Mike\'s Vet have an ICU?', a: "Yes. We have a full veterinary ICU unit with precision oxygen therapy (21–65% adjustable), controlled temperature and humidity, UV sterilisation (99.9% pathogen reduction), and nebulisation therapy. Critically ill patients can receive intensive care on-site without being transferred to another facility." },
      { q: 'Are you open for emergencies in the evenings?', a: "We are open 7 days a week from 9:00 AM to 9:30 PM including public holidays. For after-hours emergencies, call us and we will advise on the nearest available emergency care." },
      { q: 'What are the signs my pet needs emergency care?', a: "Seek urgent help for: difficulty breathing, collapse or extreme weakness, suspected poisoning, uncontrolled bleeding, inability to urinate (especially male cats), bloated or painful abdomen, seizures, or any sudden and severe change in your pet's condition." },
      { q: 'My cat is straining to urinate — is that an emergency?', a: "Yes, especially in male cats. A blocked bladder is a life-threatening emergency. If your cat is straining without producing urine, crying, licking at the genitals, or vomiting, bring them to us immediately." },
    ],
  },
]

export function getService(slug: string): Service | undefined {
  return services.find(s => s.slug === slug)
}
